//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerkleyUpdateCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>PB DSU{$*$}15:30 - 15:45</string>
  <string>PB DSU + Refinement{$*$}15:30 - 17:30</string>
  <string>PB DSU + Retro{$*$}15:00 - 16:00</string>
  <string>PB DSU + Sprint Planning + Refinement{$*$}15:00 - 17:30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeTimeMappings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeTimeMappings"]));
            }
            set {
                this["TypeTimeMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JiraTicketChecked {
            get {
                return ((bool)(this["JiraTicketChecked"]));
            }
            set {
                this["JiraTicketChecked"] = value;
            }
        }
    }
}
